#!/bin/bash

BASE_PATH=$(dirname $(realpath $0))
VM="syn-vm"
DEBUG=""
COMPILE_ONLY=""
TRACE=""

while getopts ":otdcCjh" opt; do
  case ${opt} in
    o )
        COMPILE_ONLY="true"
      ;;
    d )
        DEBUG="-d"
      ;;
    c )
        VM="$BASE_PATH/c/bin/synvmc"
      ;;
    C )
        VM="dotnet $BASE_PATH/cs/synsharp/bin/Debug/netcoreapp2.0/synsharp.dll"
      ;;
    j )
        VM="node $BASE_PATH/synvm/vm.js"
      ;;
    t )
        TRACE="-t"
      ;;
    h )
        echo "Usage: syn-run [-d] [-t] [-c] [-C] [-j] <program_name(.bc)>"
        echo "-o: only compile, do not run"
        echo "-t: enable vm tracing"
        echo "-d: enable debugging (Currently only works with the js vm)"
        echo "-c: use c vm"
        echo "-C: use csharp vm"
        echo "-j: use javascript vm (default)"
        exit 0
      ;;
  esac
done
shift $((OPTIND -1))

NAME=$(echo $1 | cut -d'.' -f 1)

dotnet $BASE_PATH/cs/syncomp/Syncomp.Cli/bin/Debug/netcoreapp2.0/Syncomp.Cli.dll $NAME.bc &&
$BASE_PATH/synasm/asm.js $NAME.asm && [ -z $COMPILE_ONLY ] &&
$VM $DEBUG $TRACE -b $NAME.bin
