#!/bin/bash

VM="syn-vm"
DEBUG=""
COMPILE_ONLY=""
TRACE=""

while getopts ":otdcCjh" opt; do
  case ${opt} in
    o )
        COMPILE_ONLY="true"
      ;;
    d )
        DEBUG="-d"
      ;;
    c )
        VM="$HOME/Source/Synacle/c/bin/synvmc"
      ;;
    C )
        VM="dotnet $HOME/Source/Synacle/cs/synsharp/bin/Debug/netcoreapp2.0/synsharp.dll"
      ;;
    j )
        VM="syn-vm"
      ;;
    t )
        TRACE="-t"
      ;;
    h )
        echo "Usage: syn-run [-d] [-t] [-c] [-C] [-j] <program_name(.bc)>"
        echo "-o: only compile, do not run"
        echo "-t: enable vm tracing"
        echo "-d: enable debugging (Currently only works with the js vm)"
        echo "-c: use c vm"
        echo "-C: use csharp vm"
        echo "-j: use javascript vm (default)"
        exit 0
      ;;
  esac
done
shift $((OPTIND -1))

NAME=$(echo $1 | cut -d'.' -f 1)


dotnet ~/Source/Synacle/cs/syncomp/Syncomp.Cli/bin/Debug/netcoreapp2.0/Syncomp.Cli.dll $NAME.bc &&
syn-asm $NAME.asm && [ -z $COMPILE_ONLY ] &&
$VM $DEBUG $TRACE -b $NAME.bin
