name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: 12

    - name: build with dotnet (compiler)
      run: dotnet build cs/syncomp/Syncomp.sln

    - name: run csharp tests (compiler)
      run: cd cs/syncomp/Syncomp.Tests/ && dotnet test

    - name: build csharp vm
      run: cd cs/synsharp && dotnet build

    - name: build c vm
      run: cd c && make

    - name: npm install (js vm)
      run: npm install

    - name: Build bc tests
      run: "./syn-run -o cs/syncomp/Syncomp.Cli/programs/tests/stdlib.bc"

    - name: Run bc tests (c vm)
      run: "OUTPUT=$(c/bin/synvmc -b cs/syncomp/Syncomp.Cli/programs/tests/stdlib.bin) && printf $OUTPUT;! printf $OUTPUT | grep 'FAILED' > /dev/null"

    - name: Run bc tests (csharp vm)
      run: "OUTPUT=$(dotnet run --no-build --project cs/synsharp/synsharp.csproj -b cs/syncomp/Syncomp.Cli/programs/tests/stdlib.bin) && printf $OUTPUT;! printf $OUTPUT | grep 'FAILED' > /dev/null"

    - name: Run bc tests (js vm)
      run: "OUTPUT=$(synvm/vm.js -b cs/syncomp/Syncomp.Cli/programs/tests/stdlib.bin) && printf $OUTPUT;! printf $OUTPUT | grep 'FAILED' > /dev/null"
