name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Build with dotnet
      run: cd cs/syncomp/Syncomp.sln
    - name: Run CSharp tests
      run: cd cs/syncomp/Syncomp.Tests/ && dotnet test
    - name: Run bc tests
      run: "./syn-run cs/syncomp/Syncomp.Cli/programs/tests/stdlib.bc"
